[build]
  command = "echo 'Nothing to build here'"
  publish = "website"

[[redirects]]
  from = "/pixel"
  to = "https://pixel.essenmitsosse.de"
  status = 301

[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [[plugins.inputs.audits]]
    url = "https://essenmitsosse.de"

  [[plugins.inputs.audits]]
    url = "https://essenmitsosse.de/older-paintings"

  [[plugins.inputs.audits]]
    url = "https://essenmitsosse.de/the-designs-of-star-wars"
