import { Analytics } from '@vercel/analytics/next'
import { SpeedInsights } from '@vercel/speed-insights/next'

import './globals.scss'

import type { ReactNode } from 'react'

export const metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
}

const Layout = ({ children }: { readonly children: ReactNode }): ReactNode => (
  <html lang="en">
    <body>
      {children}
      <Analytics />
      <SpeedInsights />
    </body>
  </html>
)

export default Layout
