import './globals.scss'

export const metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
}

export default function RootLayout({
  children,
}: {
  readonly children: React.ReactNode
}) {
  return <html lang="en">{children}</html>
}
