import type { ReactNode } from 'react'

import './globals.scss'

export const metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
}

const Layout = ({ children }: { readonly children: ReactNode }): ReactNode => (
  <html lang="en">{children}</html>
)

export default Layout
